name: Deployment

on:
  push:
    branches:
      - master

jobs:
 deployment:
    runs-on: macos-latest
    environment: 
      name: production
      url: https://github.com/galihg/ios-short-continuous-integration
      name: staging
      url: https://github.com/galihg/ios-short-continuous-integration/staging
      name: development
      url: https://github.com/galihg/ios-short-continuous-integration/development
